### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by JohnDietrich123** [sourceryltd/MakerHub-Config-Patcher#1]
Kevin,

I had no issues uploading the binary however, without knowing where to place or how to use the config files, it still defaults to the original server targets.

thanks for the patchwork!

**Comment by kevinjohnson123** [comment]
the patcher will automatically write the makerhub config files to the correct place.  If you would like to know the details of where they're being put  you can checkout the  Python script in the main repository branch for this project.
As long as the command line output shows:   "Finished...",  then it should be good.  

on MacOS the files will be located in:

/Users/{your user name goes here}/.makerverse

on Linux based systems it will be

/home/{your user name goes here}/.makerverse

If you want to manually verify that the patcher tool is working correctly  you can manually delete the .makerverse  file  Then run the patcher tool.  After that you should see the  .makerverse file appear in the appropriate directory.   If you can't find the .makerverse file  after the first run of MakerHub,  you may have to enable  "Show hidden files" in your file manager.

I've tested on  Windows 7 and the latest version of MacOS (Apple Silicon M1) and have not had any problems.  If you do, let me know and i'll get it fixed.

**Comment by JohnDietrich123** [comment]
@kevinjohnson123 ,

I have tried this in so many ways after completely deleting everything .maker and none of the ways have resulted in anything updating the config.  Perhaps I am just doing it wrong.

After a complete clean install, I opened Maker then, closed it.  I have opened it with Terminal and here is where I am at in terminal, can you walk me through it? :

Last login: Wed Dec 20 11:34:38 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Johns-MacBook-Pro:MakerHub.app johndietrich$

**Comment by kevinjohnson123** [comment]
it's fairly easy. 

-  Install MakerHub as normal
-  open MakerHub, let it load to the main screen. It might ask you to do a "Guest Login". Just Click login (it won't ask for a password since it's an offline application)
- close MakerHub
- Open the folder  /Users/{your user name goes here}/
    this should be your home directory.   
-  Press all 3 keys at once:    Shift + Command +  .
   -  this will enable you to see hidden files in your home folder
- you should be able to see a   .makerverse   file  and a  folder named   .makerverse-sessions
  these will be overwritten
  
  here's what mine looks like :
  
  
<img width="1728" alt="Screenshot 2023-12-21 at 11 11 57 PM" src="https://github.com/sourceryltd/MakerHub-Config-Patcher/assets/19762509/f5744240-0a04-404f-8c68-25db60020c49">

These two files will be overwritten by the patcher tool.

to patch the easiest way is to just open the folder where the patcher tool is downloaded  and double click it.   You should see the following text scroll up on the screen:

Getting Machine Configuration from Server...
Getting Machine Autherization token fron Server...
MacOS Detected...
...Finished

that's it.  The patcher pulls the  Default Machine Configuration a JSON authentication file from the current github repository and puts it into the  home directory.

Once that is finished, you can restart MakerHub and you should see  Machine Configurations for the M2  populated  Already.

If you're still having problems, send me a screen recording and i'll see if i might have missed anything in the walkthrough.

**Comment by JohnDietrich123** [comment]
@kevinjohnson123,

I finally figured out what was happening.  My fault mostly.

When I download the files, my Mac unpacks them automatically.  I also use my Mac for coding so, whenever I would click on any of the files it would open Xcode (idiot mistake number 1).  Since the files weren't an executable, the overall process failed or simply didn't launch.

I ended up manually adding the code into the appropriate files... BINGO!

I had my old MacBook laying around so I figured I would see what would happen if I bundled the actual files into an executable.  Doing that, NO ISSUES.

Hopefully this helps others who experience similar issues.

I sincerely want to thank you for your help and responses.  I'll close this issue tomorrow after its been read.

Happy Holidays!  Thanks again.
